"""create initial tables

Revision ID: cce8e15cbb1e
Revises: 
Create Date: 2026-08-23 14:49:19.277441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cce8e15cbb1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('principal_type', postgresql.ENUM('API_KEY', 'EXTENSION', name='principal_type'), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('entra_object_id', sa.String(), nullable=True),
    sa.Column('hashed_secret', sa.String(), nullable=False),
    sa.Column('security_policy', postgresql.ENUM('BLOCK', 'MASK', 'MONITOR', name='security_policy'), nullable=False),
    sa.Column('chatbot_category', postgresql.ENUM('CUSTOMER_SUPPORT', 'INTERNAL_EMPLOYEE', 'REGULATED_DECISION', name='chatbot_category'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_principal_id'), 'api_keys', ['principal_id'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('principal_type', postgresql.ENUM('API_KEY', 'EXTENSION', name='principal_type'), nullable=False),
    sa.Column('monthly_limit_usd', sa.Float(), nullable=False),
    sa.Column('spent_usd', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('parent_budget_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_budget_id'], ['budgets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_principal_id'), 'budgets', ['principal_id'], unique=True)
    op.create_table('request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.String(), nullable=False),
    sa.Column('principal_type', postgresql.ENUM('API_KEY', 'EXTENSION', name='principal_type'), nullable=False),
    sa.Column('chatbot_category', postgresql.ENUM('CUSTOMER_SUPPORT', 'INTERNAL_EMPLOYEE', 'REGULATED_DECISION', name='chatbot_category'), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('response_raw', sa.Text(), nullable=False),
    sa.Column('response_final', sa.Text(), nullable=False),
    sa.Column('verdict', postgresql.ENUM('PASS', 'MASK', 'BLOCK', 'REVIEW', name='verdict'), nullable=False),
    sa.Column('corrections_applied', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('flagged_reasons', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_principal_id'), 'request_logs', ['principal_id'], unique=False)
    op.create_index(op.f('ix_request_logs_verdict'), 'request_logs', ['verdict'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_log_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('proposed_response', sa.Text(), nullable=False),
    sa.Column('flagged_reason', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('action_taken', postgresql.ENUM('APPROVE', 'EDIT', 'OVERRIDE', name='review_action'), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_log_id'], ['request_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_log_id')
    )
    op.create_index(op.f('ix_review_items_resolved'), 'review_items', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_resolved'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_request_logs_verdict'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_principal_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_budgets_principal_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_api_keys_principal_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
